MyDev Project/src/objects/ApexSample__c.object
<CustomObject>
    <fields>
        <fullName>PickSomeValue__c</fullName>
        <label>PickSomeValue</label>
        <picklist>
            <picklistValues>
                <fullName>Value1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Value2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>value13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>value14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>value15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ApexSample</label>
    <nameField>
        <label>ApexSample Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApexSamples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev Project/src/classes/distinct.cls
public class distinct {
	private  Set<String> pk;
	private List<ApexSample__c> ax;
    public distinct(){
       
    }
    public void getDistinctNumber(){
       
        pk = new Set<String>();
        ax=new List<ApexSample__c>();
        ax=[select PickSomeValue__c from ApexSample__c];
        for (ApexSample__c i:ax)
		{
    		pk.add(i.PickSomeValue__c); 
		} 
         System.debug('string');
        System.debug(pk);
    }
   
}