MyDev Project/src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Ticket_description__c</fullName>
        <label>Ticket_description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>feed_back__c</fullName>
        <label>feed back</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ticket_f__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ticket</label>
        <referenceTo>ticket__c</referenceTo>
        <relationshipLabel>Feedbackks</relationshipLabel>
        <relationshipName>Feedbackks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Feedback id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbackks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/objects/ticket__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ticket</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/classes/FeedBackController.cls
public class FeedBackController {
    Private Id tid;
    public string feedback {get;set;}
    public string q1{get;set;}
    public FeedBackController(ApexPages.StandardController controller) {
   tid=Apexpages.currentpage().getparameters().get('id'); 
    }
       public FeedBackController() {
 tid=Apexpages.currentpage().getparameters().get('id');
    }
   
    public  pagereference save(){
          list<ticket__c> tik=new    List<ticket__c>();
       tik=[select name ,Description__c from ticket__c where  id=:tid ];   
        Feedback__c f=new Feedback__c();
        if(tik!=null){
        for(ticket__c tc:tik){
       f.ticket_f__c=tc.Id ;
        f.Ticket_description__c=tc.Description__c;
      }
         }
        system.debug(feedback);
        f.feed_back__c=feedback;        
       insert f;
       return null;
    }    
}